import {IPatientFull} from "../../../models/IPatientFull";

export const initialPatientState: IPatientFull = {

        patient_id: -1,
        employee_id: -1,

        personal_data: {
            first_name: '',
            second_name: '',
            patronymic: '',
            birthday: 0,
            sex: true,
            region: '',
            clinic: '',
            race: '',
            version: 0,
        },
        anthropometric_data: {
            height: 0,
            weight: 0,
            body_mass_index: 0,
            body_surface_area: 0,
            body_type: '',
            connective_tissue_dysplasia: false,
            connective_tissue_dysplasia_EhlersDanlos: false,
            connective_tissue_dysplasia_Marfan: false,
            connective_tissue_dysplasia_LoeysDitz: false,
            connective_tissue_dysplasia_Noonan: false,
            connective_tissue_dysplasia_Terner: false,
            version: 0,
            date: 0
        },

        clinical_data: {
            main_diag: "",
            aortic_dissection: false,
            intramural_hematoma: false,
            aortic_rupture: false,
            patient_state: "",
            pain_beh_stern: false,
            interscap_reg_pain: "",
            conscious_loss: "",
            low_extrem_ischemia: "",
            version: 0,
            date: 0,
        },

        concom_desease: {
            acuteMyocardilInfarctionNum: 0,
            currentMyocardilInfarction: false,
            diabetes: false,
            diabetesType: "",
            cerebrovascularDisease: false,
            BCAStenosis: false,
            translschAttack: false,
            ACVA: false,
            chronicLungDisease: false,
            prevInfectiousDisease: false,
            rhythmConcluctionDisturbances: false,
            thyroidDisease: false,
            acuteRenalFailure: false,
            chronicRenalFailure: false,
            oncology: false,
            hematologicalDisease: false,
            pulmonaryEmbolism: false,
            chestWallInjury: false,
            aorticValve: "",
            acquiredAVDisease: false,
            AVDegenerativeLesions: false,
            AVInfectiousLesions: false,
            AVWTraumaticLesionsb: false,
            version: 0,
            date: 0
        },

        echocardiogram: {
            LVEF: "",
            LVEDV: "",
            LVESV: "",
            ascAorticD: "",
            valsalvaSinusesD: "",
            AVLeafletN: "",
            AVAnnuFibrD: "",
            peakSpeedAV: "",
            AVPressureGradientMax: "",
            AVPressureGradientMean: "",
            aorticRegurgitationDegree: false,
            pulmArterySysBP: "",
            mitralInsuffStenPrD: "",
            tricuspi: "",
            trialSeptalDefectPr: "",
            version: 0,
            date: 0
        },

        anamnesis: {
            disHeartBloodVesselsFirstLineRelatives: false,
            relativesConnTissDysplasia: false,
            heartSurgeriesPr: false,
            heartSurgeriesType: "",
            geneticAnalysisPr: false,
            geneticAnalysisRes: "",
            smokingExperience: 0,
            alkoConsumptionExperince: 0,
            drugConsumptionExperince: 0,
            occupationalHazards: "",
            sports: "",
            diseaseKnowledge: 0,
            employed: false,
            blodThinDrugs: false,
            disaggregants: false,
            version: 0,
            date: 0
        },

        MCT: {
            AV_annulus_fibrosis: 0,
            sinuses_valsalva: 0,
            sinotubular_junction: 0,
            asc_aorta_pulm_art_bif: 0,
            asc_aorta_before_BCS: 0,
            aortic_arch_before_CCA: 0,
            aortic_arch_before_LSA: 0,
            aorticlsthmus: 0,
            desc_aorta_middle_part: 0,
            abdominal_aorta: 0,
            version: 0,
            date: 0
        }

}